"use client";

import { useRef, useState } from "react";
import { Upload, Trash2 } from "lucide-react";
import type { AppSettings, FlowState } from "@/lib/types";
import { exportState, importState } from "@/lib/storage";
import { toCsv, toIcs } from "@/lib/calendar-export";

function download(name:string,content:string,type:string){const url=URL.createObjectURL(new Blob([content],{type}));const anchor=document.createElement("a");anchor.href=url;anchor.download=name;anchor.click();URL.revokeObjectURL(url);}

export function SettingsPanel({ state, onReplace, onSettings, onAddCategory, onDeleteCategory }: { state:FlowState; onReplace:(state:FlowState)=>void; onSettings:(settings:AppSettings)=>void; onAddCategory:(name:string)=>void; onDeleteCategory:(id:string)=>void }) {
  const file=useRef<HTMLInputElement>(null); const [preview,setPreview]=useState<FlowState|null>(null); const [importSource,setImportSource]=useState(""); const [mode,setMode]=useState<"merge"|"replace">("merge"); const [category,setCategory]=useState("");
  return <div className="flow-form flow-stagger space-y-5">
    <section className="flow-card rounded-2xl p-4"><h2 className="font-bold">หน้าตาและเวลา</h2><label className="mt-3 block text-sm">ธีม<select value={state.settings.theme} onChange={e=>onSettings({...state.settings,theme:e.target.value as AppSettings["theme"]})} className="mt-1 h-12 w-full rounded-xl border border-[var(--flow-line)] bg-[var(--flow-paper)] px-3"><option value="system">ตามระบบ</option><option value="light">สว่าง</option><option value="dark">มืด</option></select></label><div className="mt-3 grid grid-cols-2 gap-2 [&>*]:min-w-0"><label className="text-sm">เริ่มไทม์ไลน์<input type="number" min="0" max={state.settings.timelineEndHour-1} value={state.settings.timelineStartHour} onChange={e=>onSettings({...state.settings,timelineStartHour:Math.min(Number(e.target.value),state.settings.timelineEndHour-1)})} className="font-grotesk mt-1 h-12 w-full rounded-xl border px-3"/></label><label className="text-sm">จบไทม์ไลน์<input type="number" min={state.settings.timelineStartHour+1} max="24" value={state.settings.timelineEndHour} onChange={e=>onSettings({...state.settings,timelineEndHour:Math.max(Number(e.target.value),state.settings.timelineStartHour+1)})} className="font-grotesk mt-1 h-12 w-full rounded-xl border px-3"/></label></div></section>
    <section className="flow-card rounded-2xl p-4"><h2 className="font-bold">หมวดหมู่</h2><div className="mt-3 flex gap-2"><input value={category} onChange={e=>setCategory(e.target.value)} placeholder="ชื่อหมวดหมู่" aria-label="ชื่อหมวดหมู่ใหม่" className="h-12 min-w-0 flex-1 rounded-xl border border-[var(--flow-line)] bg-transparent px-3"/><button type="button" className="flow-press flow-inverse h-12 rounded-xl px-4 font-semibold" onClick={()=>{if(category.trim()){onAddCategory(category.trim());setCategory("");}}}>เพิ่ม</button></div><ul className="mt-2">{state.categories.map(c=><li key={c.id} className="flex min-h-11 items-center justify-between border-b flow-hairline"><span>{c.name}</span><button type="button" aria-label={`ลบหมวด ${c.name}`} className="flow-press grid h-11 w-11 place-items-center rounded-xl" onClick={()=>onDeleteCategory(c.id)}><Trash2 size={16}/></button></li>)}</ul></section>
    <section className="flow-card rounded-2xl p-4"><h2 className="font-bold">ข้อมูลของฉัน</h2><p className="mt-1 text-xs text-[var(--flow-muted)]">ข้อมูลอยู่ใน browser เครื่องนี้ โปรด export สำรองไว้ก่อนล้างข้อมูลเว็บไซต์</p><div className="mt-3 grid grid-cols-3 gap-2"><button type="button" className="flow-press min-h-12 rounded-xl border border-[var(--flow-line)] text-sm" onClick={()=>download("flow-data.json",exportState(state),"application/json")}>JSON</button><button type="button" className="flow-press min-h-12 rounded-xl border border-[var(--flow-line)] text-sm" onClick={()=>download("flow-tasks.csv",toCsv(state),"text/csv")}>CSV</button><button type="button" className="flow-press min-h-12 rounded-xl border border-[var(--flow-line)] text-sm" onClick={()=>download("flow-calendar.ics",toIcs(state),"text/calendar")}>ICS</button></div><input ref={file} type="file" accept="application/json,.json" className="sr-only" onChange={async e=>{const selected=e.target.files?.[0];if(selected){const source=await selected.text();setImportSource(source);setPreview(importState(source,state,mode));}}}/><button type="button" className="flow-press flow-inverse mt-3 flex h-12 w-full items-center justify-center gap-2 rounded-xl font-semibold" onClick={()=>file.current?.click()}><Upload size={17}/>นำเข้า JSON</button>{preview&&<div className="flow-expand mt-3 rounded-xl bg-[var(--flow-lime)] p-3 text-[#111111]"><p className="font-semibold">ตัวอย่างก่อนนำเข้า: <span className="font-grotesk">{Object.values(preview.tasksByDay).flat().length}</span> งาน</p><select value={mode} onChange={e=>{const nextMode=e.target.value as "merge"|"replace";setMode(nextMode);if(importSource)setPreview(importState(importSource,state,nextMode));}} className="mt-2 h-11 w-full rounded-lg border bg-[var(--flow-paper)] px-2 text-[var(--flow-ink)]"><option value="merge">รวมกับข้อมูลเดิม</option><option value="replace">แทนที่ข้อมูลเดิม (มี backup ก่อน)</option></select><button type="button" className="flow-press mt-2 h-11 w-full rounded-lg bg-[#111111] font-semibold text-white" onClick={()=>{onReplace(preview);setPreview(null);setImportSource("");}}>ยืนยันนำเข้า</button></div>}</section>
    <section className="flow-surface rounded-2xl border-[1.5px] border-[var(--flow-line)] p-4"><h2 className="font-bold">การเชื่อมต่อ</h2><p className="mt-2 text-sm"><strong>Cloud Sync:</strong> ยังไม่ได้ตั้งค่า Supabase — ขณะนี้เป็น Guest mode และเก็บข้อมูลในเครื่อง</p><p className="mt-2 text-sm"><strong>Google Calendar:</strong> ยังไม่ได้ตั้งค่า OAuth — ใช้ ICS export ด้านบนได้</p><p className="mt-2 text-xs text-[var(--flow-muted)]">เราไม่สร้างระบบจำลองและไม่ส่ง API key จากฝั่ง client</p></section>
    <a href="/policy" className="flex min-h-11 items-center underline">นโยบายการใช้งานเว็บไซต์</a>
  </div>;
}
