"use client";

import { useEffect, useMemo, useState } from "react";
import Link from "next/link";
import dynamic from "next/dynamic";
import { BarChart3, CalendarDays, ChevronLeft, ChevronRight, Clock3, Focus, LayoutList, ListTodo, LogOut, Map as MapIcon, Search, Settings, Sparkles, Undo2, WifiOff } from "lucide-react";
import { MonthGrid } from "@/components/MonthGrid";
import { PwaRegister } from "@/components/PwaRegister";
import { DashboardPanel } from "@/components/planner/DashboardPanel";
import { DayTimeline } from "@/components/planner/DayTimeline";
import { FocusPanel } from "@/components/planner/FocusPanel";
import { SearchPanel } from "@/components/planner/SearchPanel";
import { SettingsPanel } from "@/components/planner/SettingsPanel";
import { TaskComposer, type RepeatDraft } from "@/components/planner/TaskComposer";
import { TaskListView } from "@/components/planner/TaskListView";
import { TodayPulse } from "@/components/planner/TodayPulse";
import { FlowDialog as Modal } from "@/components/ui/flow-dialog";
import { replaceFlow } from "@/lib/flow-store";
import { getDueReminders, type DueReminder } from "@/lib/reminders";
import { mergeOccurrences, occurrencesForRange } from "@/lib/recurrence";
import { localDateKey } from "@/lib/time";
import { TaskSchema, type DayEnergy, type FlowState, type FocusSession, type PlanResult, type Task } from "@/lib/types";
import { useFlowStore } from "@/hooks/useFlowStore";

type Tab = "today" | "calendar" | "dashboard" | "search" | "settings";
type DayView = "list" | "timeline" | "focus" | "map";

const THAI_MONTHS=["มกราคม","กุมภาพันธ์","มีนาคม","เมษายน","พฤษภาคม","มิถุนายน","กรกฎาคม","สิงหาคม","กันยายน","ตุลาคม","พฤศจิกายน","ธันวาคม"];
const pad=(value:number)=>String(value).padStart(2,"0");
const dateKey=(year:number,month:number,day:number)=>`${year}-${pad(month+1)}-${pad(day)}`;
const FlowMap=dynamic(()=>import("@/components/FlowMap").then(module=>module.FlowMap),{ssr:false,loading:()=> <div className="flow-surface grid min-h-72 place-items-center rounded-2xl border border-[var(--flow-line)] text-sm text-[var(--flow-muted)]">กำลังเปิดแผนที่…</div>});

function dateParts(value:string){const [year,month,day]=value.split("-").map(Number);return{year,month:month-1,day};}
function uid(prefix:string){return `${prefix}-${crypto.randomUUID()}`;}

export default function Home(){
  const {state,updateFlow}=useFlowStore();
  const [tab,setTab]=useState<Tab>("today");
  const [dayView,setDayView]=useState<DayView>("list");
  const [selectedDate,setSelectedDate]=useState(localDateKey());
  const parts=dateParts(selectedDate);
  const [monthCursor,setMonthCursor]=useState({year:parts.year,month:parts.month});
  const [undo,setUndo]=useState<{label:string;state:FlowState}|null>(null);
  const [categoryFilter,setCategoryFilter]=useState("");
  const [online,setOnline]=useState(true);
  const [aiOpen,setAiOpen]=useState(false);
  const [parsedDraft,setParsedDraft]=useState<Task[]|null>(null);
  const [aiError,setAiError]=useState("");
  const [planDraft,setPlanDraft]=useState<PlanResult|null>(null);
  const [planning,setPlanning]=useState(false);
  const [activeReminder,setActiveReminder]=useState<DueReminder|null>(null);
  const [carryOpen,setCarryOpen]=useState(false);
  const baseTasks=useMemo(()=>state.tasksByDay[selectedDate]??[],[selectedDate,state.tasksByDay]);
  const tasks=useMemo(()=>{
    const templates=Object.values(state.tasksByDay).flat();
    const generated=state.recurrenceRules.flatMap(rule=>{const template=templates.find(task=>task.id===rule.taskId);return template?occurrencesForRange(template,rule,selectedDate,selectedDate):[];});
    return mergeOccurrences(baseTasks,generated);
  },[baseTasks,selectedDate,state.recurrenceRules,state.tasksByDay]);
  const shownTasks=categoryFilter?tasks.filter(task=>task.categoryId===categoryFilter):tasks;

  useEffect(()=>{const sync=()=>setOnline(navigator.onLine);sync();window.addEventListener("online",sync);window.addEventListener("offline",sync);return()=>{window.removeEventListener("online",sync);window.removeEventListener("offline",sync);};},[]);
  useEffect(()=>{const root=document.documentElement;const dark=state.settings.theme==="dark"||(state.settings.theme==="system"&&matchMedia("(prefers-color-scheme: dark)").matches);root.dataset.theme=dark?"dark":"light";},[state.settings.theme]);
  useEffect(()=>{if(!undo)return;const timer=window.setTimeout(()=>setUndo(null),8000);return()=>window.clearTimeout(timer);},[undo]);
  useEffect(()=>{if(!state.settings.notificationsEnabled)return;const check=()=>{const notified=new Set(state.reminderLog.map(item=>item.id));const due=getDueReminders(state.tasksByDay,new Date(),notified);if(!due.length)return;setActiveReminder(due[0]);due.forEach(item=>{if(Notification.permission==="granted")new Notification(item.task.title,{body:`เริ่ม ${item.task.fixedTime} · ${item.task.place||"ไม่มีสถานที่"}`,tag:item.id});});updateFlow(previous=>({...previous,reminderLog:[...previous.reminderLog,...due.map(item=>({id:item.id,taskId:item.task.id,occurrenceDate:item.date,offsetMin:item.offsetMin,notifiedAt:new Date().toISOString()}))]}));};const timer=window.setInterval(check,30_000);return()=>window.clearInterval(timer);},[state.settings.notificationsEnabled,state.reminderLog,state.tasksByDay,updateFlow]);

  const commit=(recipe:(previous:FlowState)=>FlowState,label?:string)=>{if(label)setUndo({label,state});updateFlow(recipe);};
  const setDayTasks=(next:Task[],label?:string)=>commit(previous=>({...previous,tasksByDay:{...previous.tasksByDay,[selectedDate]:next.map(task=>TaskSchema.parse(task))}}),label);
  const addTask=(task:Task,repeat:RepeatDraft)=>{const now=new Date().toISOString();commit(previous=>{const recurrenceRules=[...previous.recurrenceRules];let nextTask=task;if(repeat.frequency!=="none"){const ruleId=uid("series");recurrenceRules.push({id:ruleId,taskId:task.id,frequency:repeat.frequency,interval:1,weekdays:repeat.frequency==="weekly"?[new Date(`${selectedDate}T12:00`).getDay()]:[],startDate:selectedDate,excludedDates:[],createdAt:now,updatedAt:now});nextTask={...task,seriesId:ruleId,occurrenceDate:selectedDate};}return{...previous,tasksByDay:{...previous.tasksByDay,[selectedDate]:[...(previous.tasksByDay[selectedDate]??[]),TaskSchema.parse(nextTask)]},recurrenceRules};},"เพิ่มงานแล้ว");};
  const updateTask=(next:Task)=>setDayTasks(tasks.map(task=>task.id===next.id?next:task),"เปลี่ยนเวลาแล้ว");
  const removeTask=(id:string)=>setDayTasks(tasks.filter(task=>task.id!==id),"ลบงานแล้ว");
  const toggleTask=(id:string)=>setDayTasks(tasks.map(task=>task.id===id?{...task,done:!task.done,completedAt:!task.done?new Date().toISOString():undefined,updatedAt:new Date().toISOString()}:task),"อัปเดตงานแล้ว");
  const selectDate=(date:string)=>{setSelectedDate(date);const next=dateParts(date);setMonthCursor({year:next.year,month:next.month});setTab("today");};
  const changeDay=(offset:number)=>{const date=new Date(`${selectedDate}T12:00:00`);date.setDate(date.getDate()+offset);selectDate(localDateKey(date));};
  const focusComplete=(session:FocusSession,updateDuration:boolean)=>commit(previous=>({...previous,focusSessions:[...previous.focusSessions,session],tasksByDay:updateDuration&&session.taskId?Object.fromEntries(Object.entries(previous.tasksByDay).map(([date,items])=>[date,items.map(task=>task.id===session.taskId?{...task,durationMin:session.actualMin||task.durationMin,updatedAt:new Date().toISOString()}:task)])):previous.tasksByDay}),"บันทึก Focus แล้ว");
  const monthLoad=useMemo(()=>Object.fromEntries(Object.entries(state.tasksByDay).filter(([date])=>date.startsWith(`${monthCursor.year}-${pad(monthCursor.month+1)}`)).map(([date,items])=>[Number(date.slice(-2)),Math.min(1,items.length/6)])),[state.tasksByDay,monthCursor]);
  const pastUnfinished=Object.entries(state.tasksByDay).filter(([date])=>date<localDateKey()).flatMap(([date,items])=>items.filter(task=>!task.done).map(task=>({date,task}))).slice(0,20);

  const requestNotifications=async()=>{if(!("Notification" in window))return;const permission=await Notification.requestPermission();if(permission==="granted")updateFlow(previous=>({...previous,settings:{...previous.settings,notificationsEnabled:true}}));};
  const parseNaturalLanguage=async(form:HTMLFormElement)=>{setAiError("");const text=String(new FormData(form).get("text")??"");try{const response=await fetch("/api/parse",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({text,nowIso:new Date().toISOString(),timezone:"Asia/Bangkok",selectedDate})});if(!response.ok)throw new Error("parse");const json=await response.json() as {tasks?:unknown[]};const safe=(json.tasks??[]).map(item=>{const record=typeof item==="object"&&item!==null?item:{};return TaskSchema.safeParse({...record,id:uid("ai"),place:(record as {place?:string}).place??"",createdAt:new Date().toISOString(),updatedAt:new Date().toISOString()});}).filter(result=>result.success).map(result=>result.data);setParsedDraft(safe);}catch{setAiError(online?"ยังวิเคราะห์ไม่ได้ กรุณาลองใหม่":"AI ใช้งานไม่ได้ขณะออฟไลน์");}};
  const buildPlan=async()=>{setPlanning(true);setAiError("");try{const response=await fetch("/api/plan",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({tasks,selectedDate,energy:state.dayMetaByDay[selectedDate]?.energy??"medium",timezone:"Asia/Bangkok"})});if(!response.ok)throw new Error("plan");setPlanDraft(await response.json() as PlanResult);}catch{setAiError(online?"ยังจัดแผนไม่ได้ กรุณาตรวจการเชื่อมต่อ AI":"AI ใช้งานไม่ได้ขณะออฟไลน์");}finally{setPlanning(false);}};

  const title=tab==="today"?"วันนี้":tab==="calendar"?"ปฏิทิน":tab==="dashboard"?"ภาพรวม":tab==="search"?"ค้นหา":"ตั้งค่า";
  return <main className="min-h-dvh bg-[var(--flow-paper)] pb-[calc(7.5rem+env(safe-area-inset-bottom))] pt-[env(safe-area-inset-top)] text-[var(--flow-ink)]"><PwaRegister/><div className="mx-auto w-full max-w-[420px] px-4 pt-5">
    <header className="flow-rise mb-5 flex items-center justify-between"><div><Link href="/app" className="font-grotesk inline-flex min-h-11 items-center text-[22px] font-bold tracking-[-0.04em]">flow<span className="text-[var(--flow-lime-dark)]">_</span></Link><h1 className="-mt-0.5 text-[26px] font-bold leading-tight tracking-[-0.02em]">{title}</h1></div><div className="flex items-center gap-1.5">{!online&&<span className="flex min-h-9 items-center gap-1 rounded-full border border-[var(--flow-line)] px-2 text-xs"><WifiOff size={13}/>ออฟไลน์</span>}<Link href="/login" aria-label="ออกจาก Guest mode และกลับหน้าเข้าสู่ระบบ" className="flow-press flex min-h-11 items-center gap-1.5 rounded-xl border border-[var(--flow-line)] px-2.5 text-xs font-semibold"><span className="font-grotesk">GUEST</span><LogOut size={14} aria-hidden /></Link></div></header>

    {tab==="today"&&<>
      <div className="flow-inverse mb-3 flex items-center justify-between rounded-2xl border-[1.5px] border-[#111111] p-2 shadow-[var(--flow-shadow-small)]"><button aria-label="วันก่อนหน้า" className="grid h-11 w-11 place-items-center rounded-xl hover:bg-white/10" onClick={()=>changeDay(-1)}><ChevronLeft/></button><button className="min-h-11 rounded-xl px-4 text-center hover:bg-white/10" onClick={()=>selectDate(localDateKey())}><strong className="block">{selectedDate===localDateKey()?"วันนี้":new Intl.DateTimeFormat("th-TH",{weekday:"long"}).format(new Date(`${selectedDate}T12:00`))}</strong><span className="font-grotesk text-xs text-[var(--flow-lime)]">{selectedDate}</span></button><button aria-label="วันถัดไป" className="grid h-11 w-11 place-items-center rounded-xl hover:bg-white/10" onClick={()=>changeDay(1)}><ChevronRight/></button></div>
      <TodayPulse date={selectedDate} tasks={tasks} startHour={state.settings.timelineStartHour} endHour={state.settings.timelineEndHour} onOpenTimeline={()=>setDayView("timeline")} onStartFocus={()=>setDayView("focus")}/>
      {pastUnfinished.length>0&&selectedDate===localDateKey()&&<button className="mb-3 min-h-12 w-full rounded-xl border-[1.5px] border-amber-500 px-3 text-left text-sm font-semibold" onClick={()=>setCarryOpen(true)}>มีงานค้าง {pastUnfinished.length} งาน · เลือกย้ายมาวันนี้</button>}
      <div className="mt-5 flex gap-2 overflow-x-auto pb-2 [scrollbar-width:none] [&::-webkit-scrollbar]:hidden"><button aria-pressed={!categoryFilter} onClick={()=>setCategoryFilter("")} className={`min-h-11 shrink-0 rounded-full border px-4 text-sm ${!categoryFilter?"border-[var(--flow-ink)] bg-[var(--flow-ink)] text-[var(--flow-paper)]":"flow-hairline"}`}>ทั้งหมด</button>{state.categories.map(category=><button key={category.id} aria-pressed={categoryFilter===category.id} onClick={()=>setCategoryFilter(category.id)} className={`min-h-11 shrink-0 rounded-full border px-4 text-sm ${categoryFilter===category.id?"border-[var(--flow-ink)] bg-[var(--flow-ink)] text-[var(--flow-paper)]":"flow-hairline"}`}>{category.name}</button>)}</div>
      <div role="tablist" aria-label="รูปแบบการดูวัน" className="flow-surface mb-4 grid grid-cols-4 rounded-2xl border border-[var(--flow-line)] p-1">{[["list","รายการ",LayoutList],["timeline","เวลา",Clock3],["focus","โฟกัส",Focus],["map","แผนที่",MapIcon]].map(([value,label,Icon])=><button key={String(value)} role="tab" aria-selected={dayView===value} onClick={()=>setDayView(value as DayView)} className={`relative flex min-h-11 items-center justify-center gap-1 rounded-xl text-xs ${dayView===value?"bg-[var(--flow-ink)] text-[var(--flow-paper)] shadow-[var(--flow-shadow-small)]":"text-[var(--flow-muted)]"}`}><Icon size={15}/>{String(label)}{dayView===value&&<span aria-hidden className="absolute inset-x-3 -bottom-1 h-0.5 rounded-full bg-[var(--flow-lime)]"/>}</button>)}</div>
      <div key={`${dayView}-${selectedDate}`} className="flow-view">
        {dayView==="timeline"&&<DayTimeline date={selectedDate} tasks={shownTasks} categories={state.categories} startHour={state.settings.timelineStartHour} endHour={state.settings.timelineEndHour} onChange={updateTask} onDelete={removeTask} onToggle={toggleTask}/>} 
        {dayView==="list"&&<TaskListView tasks={shownTasks} categories={state.categories} onToggle={toggleTask} onDelete={removeTask} onAdd={()=>document.getElementById("task-composer")?.scrollIntoView({behavior:"smooth",block:"center"})}/>} 
        {dayView==="focus"&&<FocusPanel tasks={tasks} sessions={state.focusSessions} active={state.activeFocusSession} onActiveChange={activeFocusSession=>updateFlow(previous=>({...previous,activeFocusSession}))} onComplete={focusComplete}/>} 
        {dayView==="map"&&(online?<FlowMap items={tasks.filter(task=>task.fixedTime).map(task=>({taskId:task.id,title:task.title,placeLabel:task.place,start:task.fixedTime??"00:00",end:task.fixedTime??"00:00",travelFromPrevMin:0,aiAdded:task.aiAdded}))} coords={Object.fromEntries(tasks.filter(task=>task.lat!=null&&task.lng!=null).map(task=>[task.id,{lat:task.lat!,lng:task.lng!}]))}/>:<p className="flow-surface rounded-2xl border p-5 text-sm">แผนที่และเส้นทางใช้งานไม่ได้ขณะออฟไลน์</p>)}
      </div>
      <section className="flow-card my-5 rounded-2xl p-4"><h2 className="font-bold">พลังงานวันนี้</h2><div className="mt-2 grid grid-cols-3 gap-2">{(["low","medium","high"] as DayEnergy[]).map(energy=>{const selected=state.dayMetaByDay[selectedDate]?.energy===energy;return <button key={energy} aria-pressed={selected} className={`flow-press min-h-11 rounded-xl border ${selected?"border-[var(--flow-lime-dark)] bg-[var(--flow-lime)] font-bold text-[#111111]":"border-[var(--flow-line)]"}`} onClick={()=>updateFlow(previous=>({...previous,dayMetaByDay:{...previous.dayMetaByDay,[selectedDate]:{date:selectedDate,energy,note:previous.dayMetaByDay[selectedDate]?.note??""}}}))}>{energy==="low"?"น้อย":energy==="medium"?"กลาง":"มาก"}</button>;})}</div><p className="mt-2 text-xs text-[var(--flow-muted)]">{state.dayMetaByDay[selectedDate]?.energy==="low"?"ลองลดงานยืดหยุ่นและเว้นช่วงพักให้มากขึ้น":"ใช้ระดับพลังงานเป็นบริบทเมื่อให้ AI ช่วยจัดแผน"}</p></section>
      <div id="task-composer" className="my-5 scroll-mt-6"><TaskComposer categories={state.categories} date={selectedDate} order={tasks.length} onAdd={addTask}/></div>
      <div className="mb-8 grid grid-cols-2 gap-2"><button className="flow-press flex min-h-14 items-center justify-center gap-2 rounded-2xl border-[1.5px] border-[var(--flow-line)] px-2 text-sm font-semibold" onClick={()=>setAiOpen(true)} disabled={!online}><Sparkles size={18}/>เพิ่มด้วย AI</button><button className="flow-press flow-inverse flex min-h-14 items-center justify-center gap-2 rounded-2xl px-2 text-sm font-semibold" onClick={()=>void buildPlan()} disabled={!online||!tasks.length||planning}><Clock3 size={18}/>{planning?"กำลังจัด…":"จัดแผนวัน"}</button></div>{aiError&&!aiOpen&&<p role="alert" className="mb-5 rounded-xl border border-[var(--flow-warning)] p-3 text-sm font-semibold text-[var(--flow-warning)]">{aiError}</p>}
    </>}

    {tab==="calendar"&&<section className="flow-rise"><div className="mb-4 flex items-center justify-between"><button aria-label="เดือนก่อน" className="grid h-11 w-11 place-items-center" onClick={()=>setMonthCursor(current=>current.month===0?{year:current.year-1,month:11}:{...current,month:current.month-1})}><ChevronLeft/></button><h2 className="font-bold">{THAI_MONTHS[monthCursor.month]} <span className="font-grotesk">{monthCursor.year+543}</span></h2><button aria-label="เดือนถัดไป" className="grid h-11 w-11 place-items-center" onClick={()=>setMonthCursor(current=>current.month===11?{year:current.year+1,month:0}:{...current,month:current.month+1})}><ChevronRight/></button></div><MonthGrid year={monthCursor.year} month={monthCursor.month} load={monthLoad} selected={selectedDate.startsWith(`${monthCursor.year}-${pad(monthCursor.month+1)}`)?Number(selectedDate.slice(-2)):undefined} onPick={day=>selectDate(dateKey(monthCursor.year,monthCursor.month,day))}/></section>}
    {tab==="dashboard"&&<DashboardPanel state={state}/>} 
    {tab==="search"&&<SearchPanel tasksByDay={state.tasksByDay} categories={state.categories} onOpen={selectDate}/>} 
    {tab==="settings"&&<SettingsPanel state={state} onReplace={next=>{localStorage.setItem("flow_state_backup_v1",JSON.stringify(state));replaceFlow(next);}} onSettings={settings=>updateFlow(previous=>({...previous,settings}))} onAddCategory={name=>updateFlow(previous=>({...previous,categories:[...previous.categories,{id:uid("category"),name,createdAt:new Date().toISOString()}]}))} onDeleteCategory={id=>commit(previous=>({...previous,categories:previous.categories.filter(category=>category.id!==id),tasksByDay:Object.fromEntries(Object.entries(previous.tasksByDay).map(([date,items])=>[date,items.map(task=>task.categoryId===id?{...task,categoryId:undefined}:task)]))}),"ลบหมวดหมู่แล้ว")}/>} 
    {tab==="settings"&&!state.settings.notificationsEnabled&&<button className="mt-4 min-h-12 w-full rounded-xl bg-[var(--flow-lime)] px-3 font-semibold text-[#111]" onClick={requestNotifications}>เปิดการแจ้งเตือนบนอุปกรณ์นี้</button>}
  </div>
  <nav aria-label="เมนูหลัก" className="fixed inset-x-0 bottom-0 z-30 mx-auto flex min-h-20 max-w-[420px] items-start justify-around border-t border-[var(--flow-line)] bg-[color-mix(in_srgb,var(--flow-paper)_92%,transparent)] px-2 pt-2 pb-[max(.5rem,env(safe-area-inset-bottom))] shadow-[0_-10px_30px_rgba(17,17,17,.06)] backdrop-blur-xl">{[["today","วันนี้",ListTodo],["calendar","ปฏิทิน",CalendarDays],["dashboard","ภาพรวม",BarChart3],["search","ค้นหา",Search],["settings","ตั้งค่า",Settings]].map(([value,label,Icon])=><button key={String(value)} onClick={()=>setTab(value as Tab)} aria-current={tab===value?"page":undefined} className={`relative flex min-h-14 min-w-14 flex-col items-center justify-center gap-1 rounded-xl text-[10px] ${tab===value?"font-bold text-[var(--flow-ink)]":"text-[var(--flow-muted)]"}`}><span className={`grid h-7 w-9 place-items-center rounded-lg ${tab===value?"bg-[var(--flow-ink)] text-[var(--flow-lime)]":""}`}><Icon size={18} strokeWidth={tab===value?2.5:1.8}/></span>{String(label)}{tab===value&&<span aria-hidden className="absolute -top-2 h-1 w-7 rounded-b-full bg-[var(--flow-lime-dark)]"/>}</button>)}</nav>
  {undo&&<div role="status" className="flow-fade flow-inverse fixed bottom-24 left-1/2 z-50 flex w-[calc(100%-32px)] max-w-[388px] -translate-x-1/2 items-center justify-between rounded-2xl p-3 shadow-[var(--flow-shadow)]"><span>{undo.label}</span><button className="flex min-h-11 items-center gap-1 px-2 font-semibold text-[var(--flow-lime)]" onClick={()=>{replaceFlow(undo.state);setUndo(null);}}><Undo2 size={16}/>ย้อนกลับ</button></div>}
  {activeReminder&&<Modal role="alertdialog" title="ถึงเวลาแล้ว" onClose={()=>setActiveReminder(null)}><div className="rounded-2xl bg-[var(--flow-lime)] p-4 text-[#111111]"><h3 className="font-bold">{activeReminder.task.title}</h3><p className="font-grotesk mt-1 text-xs">{activeReminder.date} · {activeReminder.task.fixedTime}</p></div><div className="mt-3 grid grid-cols-3 gap-2"><button className="min-h-11 rounded-xl bg-[#111111] px-2 text-xs font-semibold text-white" onClick={()=>{updateFlow(previous=>({...previous,tasksByDay:{...previous.tasksByDay,[activeReminder.date]:(previous.tasksByDay[activeReminder.date]??[]).map(task=>task.id===activeReminder.task.id?{...task,done:true,completedAt:new Date().toISOString()}:task)}}));setActiveReminder(null);}}>เสร็จแล้ว</button><button className="min-h-11 rounded-xl border border-[var(--flow-line)] px-2 text-xs font-semibold" onClick={()=>{const reminder=activeReminder;setActiveReminder(null);window.setTimeout(()=>setActiveReminder(reminder),5*60_000);}}>เลื่อน 5 นาที</button><button className="min-h-11 rounded-xl border border-[var(--flow-line)] px-2 text-xs font-semibold" onClick={()=>{selectDate(activeReminder.date);setActiveReminder(null);}}>เปิดงาน</button></div></Modal>}
  {aiOpen&&<Modal title="เพิ่มงานด้วย AI" onClose={()=>{setAiOpen(false);setParsedDraft(null);}}><form className="flow-form" onSubmit={event=>{event.preventDefault();void parseNaturalLanguage(event.currentTarget);}}><label className="text-sm font-semibold" htmlFor="nl-task">บอกงาน เวลา สถานที่ หรือการทำซ้ำ</label><textarea id="nl-task" name="text" required rows={4} placeholder="เช่น พรุ่งนี้ประชุมทีม 10 โมง 1 ชั่วโมง เตือนก่อน 10 นาที" className="mt-2 w-full rounded-xl border-[1.5px] border-[var(--flow-line)] bg-transparent p-3"/><button className="flow-press flow-inverse mt-3 h-12 w-full rounded-xl font-semibold" type="submit">วิเคราะห์เป็นฉบับร่าง</button></form>{aiError&&<p role="alert" className="mt-3 text-sm font-semibold text-[var(--flow-warning)]">{aiError}</p>}{parsedDraft&&<div className="flow-expand mt-4"><h3 className="font-bold">ตรวจสอบก่อนเพิ่ม</h3>{parsedDraft.map(task=><article key={task.id} className="flow-surface mt-2 rounded-xl border border-[var(--flow-line)] p-3"><p className="font-semibold">{task.title}</p><p className="font-grotesk text-xs">{task.fixedTime??"ยังไม่กำหนดเวลา"} · {task.durationMin??60} min</p>{task.needsReview&&<p className="text-xs font-semibold text-[var(--flow-warning)]">ต้องตรวจสอบ: {task.note}</p>}</article>)}<button className="flow-press mt-3 h-12 w-full rounded-xl bg-[var(--flow-lime)] font-semibold text-[#111111]" onClick={()=>{setDayTasks([...tasks,...parsedDraft],"เพิ่มงานจาก AI แล้ว");setAiOpen(false);setParsedDraft(null);}}>ยืนยันเพิ่มโดยไม่แทนงานเดิม</button></div>}</Modal>}
  {planDraft&&<Modal title="ตรวจแผนก่อนใช้" onClose={()=>setPlanDraft(null)}><p className="text-sm">{planDraft.summary}</p><div className="mt-4 space-y-2">{planDraft.plans.B.schedule.map((item,index)=><article key={`${item.taskId}-${index}`} className="rounded-xl border p-3"><p className="font-semibold">{item.title}</p><p className="font-grotesk text-xs">{item.start}–{item.end} · travel {item.travelFromPrevMin} min</p>{item.aiAdded&&<p className="text-xs text-[var(--flow-muted)]">AI เสนอเพิ่ม — ยังไม่ถูกบันทึก</p>}</article>)}</div><p className="mt-3 text-sm font-semibold">คำแนะนำ: {planDraft.tip}</p><button className="mt-4 h-12 w-full rounded-xl bg-[var(--flow-lime)] font-semibold text-[#111]" onClick={()=>{const now=new Date().toISOString();const scheduled=planDraft.plans.B.schedule.map((item,index)=>{const existing=tasks.find(task=>task.id===item.taskId);const [sh,sm]=item.start.split(":").map(Number);const [eh,em]=item.end.split(":").map(Number);const duration=Math.max(15,(eh*60+em)-(sh*60+sm));return existing?TaskSchema.parse({...existing,fixedTime:item.start,durationMin:duration,updatedAt:now}):TaskSchema.parse({id:uid("ai-plan"),title:item.title,place:item.placeLabel,fixedTime:item.start,durationMin:duration,priority:"normal",aiAdded:true,order:tasks.length+index,createdAt:now,updatedAt:now});});setDayTasks(scheduled,"ใช้แผน AI แล้ว");setPlanDraft(null);}}>ใช้แผนนี้</button></Modal>}
  {carryOpen&&<Modal title="งานค้าง" onClose={()=>setCarryOpen(false)}><p className="text-sm text-[var(--flow-muted)]">เลือกงานเพื่อย้ายมาวันนี้ เวลาที่ผ่านแล้วจะถูกนำออกและอยู่ในส่วนยังไม่กำหนดเวลา</p><div className="flow-stagger">{pastUnfinished.map(({date,task})=><article key={`${date}-${task.id}`} className="flow-surface mt-2 flex items-center gap-2 rounded-xl border border-[var(--flow-line)] p-3"><div className="min-w-0 flex-1"><p className="break-words font-semibold">{task.title}</p><p className="font-grotesk text-xs">{date} · {task.fixedTime??"—"}</p></div><button className="flow-press flow-inverse min-h-11 rounded-xl px-3" onClick={()=>{const now=new Date();const current=state.tasksByDay[localDateKey()]??[];const past=task.fixedTime&&task.fixedTime<now.toTimeString().slice(0,5);commit(previous=>({...previous,tasksByDay:{...previous.tasksByDay,[date]:(previous.tasksByDay[date]??[]).filter(item=>item.id!==task.id),[localDateKey()]:[...current,TaskSchema.parse({...task,fixedTime:past?undefined:task.fixedTime,originalDate:task.originalDate??date,movedCount:(task.movedCount??0)+1,updatedAt:now.toISOString()})]}}),"ย้ายงานแล้ว");}}>ย้าย</button></article>)}</div></Modal>}
  </main>;
}
